In [2]:
import pyodbc
import pandas as pd

# Configuración de la conexión
server = 'localhost'  # Nombre o dirección del servidor SQL Server
database = 'Delitos'  # Nombre de tu base de datos
username = 'paob2'  # Usuario de SQL Server
password = 'Paulo2024$'  # Contraseña del usuario
driver = '{ODBC Driver 17 for SQL Server}'  # Asegúrate de tener el driver adecuado instalado

# Conexión a la base de datos
try:
    
    ##connection = pyodbc.connect(
    ##    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
    ##)

    connection = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes'
)
    print("Conexión exitosa a la base de datos.")

    # Creación de un cursor
    cursor = connection.cursor()

    # Ejecución de una consulta
    query = "SELECT * FROM delitos"  # Reemplaza 'TuTabla' con el nombre de tu tabla

        # Leer los datos en un DataFrame de Pandas
    df = pd.read_sql_query(query, connection)


except pyodbc.Error as e:
    print("Error al conectar a la base de datos:", e)

finally:
    # Cerrar la conexión
    if 'connection' in locals() and connection:
        connection.close()
        print("Conexión cerrada.")

df.sample(20)

Conexión exitosa a la base de datos.

C:\Users\paob2\AppData\Local\Temp\ipykernel_11292\3950391735.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

Conexión cerrada.

,Año,Clave_Ent,Entidad,Cve_Municipio,Municipio,Bien_jurídico_afectado,Tipo_de_delito,Subtipo_de_delito,Modalidad,Enero,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
312628,2017,29,Tlaxcala,29047,Lázaro Cárdenas,El patrimonio,Robo,Robo de autopartes,Sin violencia,0,...,0,0,0,0,0,0,0,0,0,0
1209282,2020,20,Oaxaca,20065,Ixpantepec Nieves,El patrimonio,Robo,Robo en transporte individual,Sin violencia,0,...,0,0,0,0,0,0,0,0,0,0
809235,2018,26,Sonora,26031,Huachinera,El patrimonio,Robo,Robo a transportista,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0
145601,2017,12,Guerrero,12004,Alcozauca de Guerrero,La vida y la Integridad corporal,Lesiones,Lesiones culposas,Con arma de fuego,0,...,0,0,0,0,0,0,0,0,0,0
1152406,2020,13,Hidalgo,13037,Metztitlán,Libertad personal,Secuestro,Secuestro,Secuestro extorsivo,0,...,0,0,0,0,0,0,0,0,0,0
1162917,2020,14,Jalisco,14060,Mexticacán,El patrimonio,Robo,Robo a transportista,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0
120952,2017,7,Chiapas,7039,Huitiupán,El patrimonio,Robo,Robo en transporte individual,Sin violencia,0,...,0,0,0,0,0,0,0,0,0,0
1324174,2020,30,Veracruz de Ignacio de la Llave,30149,Soteapan,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,...,0,0,0,0,0,0,0,0,0,0
1370910,2021,8,Chihuahua,8041,Maguarichi,La sociedad,Trata de personas,Trata de personas,Trata de personas,0,...,0,0,0,0,0,0,0,0,0,0
1345713,2020,32,Zacatecas,32049,Valparaíso,El patrimonio,Fraude,Fraude,Fraude,1,...,1,0,0,5,1,1,1,0,2,0
798046,2018,23,Quintana Roo,23004,Othón P. Blanco,La libertad y la seguridad sexual,Abuso sexual,Abuso sexual,Abuso sexual,2,...,5,6,5,5,4,2,1,5,0,1
814343,2018,27,Tabasco,27009,Jalapa,El patrimonio,Robo,Robo a institución bancaria,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0
1570611,2021,30,Veracruz de Ignacio de la Llave,30186,Tomatlán,El patrimonio,Robo,Robo a negocio,Con violencia,0,...,0,0,0,0,0,0,0,1,0,0
1476267,2021,20,Oaxaca,20311,San Pedro Jaltepetongo,Otros bienes jurídicos afectados (del fuero co...,Falsificación,Falsificación,Falsificación,0,...,0,0,0,0,0,0,0,0,0,0
1060040,2019,28,Tamaulipas,28028,Nuevo Morelos,El patrimonio,Robo,Robo de maquinaria,"Robo de cables, tubos y otros objetos destinad...",0,...,0,0,0,0,0,0,0,0,0,0
1279841,2020,21,Puebla,21214,Zinacatepec,El patrimonio,Robo,Robo en transporte individual,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0
513880,2015,13,Hidalgo,13017,Chapantongo,La vida y la Integridad corporal,Homicidio,Homicidio culposo,En accidente de tránsito,0,...,0,0,0,0,0,0,0,0,0,0
273515,2017,21,Puebla,21105,Ocotepec,La libertad y la seguridad sexual,Incesto,Incesto,Incesto,0,...,0,0,0,0,0,0,0,0,0,0
134344,2017,8,Chihuahua,8058,San Francisco de Conchos,Libertad personal,Secuestro,Secuestro,Secuestro para causar daño,0,...,0,0,0,0,0,0,0,0,0,0
1214176,2020,20,Oaxaca,20115,San Bartolo Coyotepec,El patrimonio,Robo,Robo a transeúnte en espacio abierto al público,Sin violencia,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1589462 entries, 0 to 1589461
Data columns (total 21 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Año                     1589462 non-null  int64
 1   Clave_Ent               1589462 non-null  int64
 2   Entidad                 1589462 non-null  object
 3   Cve_Municipio           1589462 non-null  int64
 4   Municipio               1589462 non-null  object
 5   Bien_jurídico_afectado  1589462 non-null  object
 6   Tipo_de_delito          1589462 non-null  object
 7   Subtipo_de_delito       1589462 non-null  object
 8   Modalidad               1589462 non-null  object
 9   Enero                   1589462 non-null  object
 10  Febrero                 1589462 non-null  object
 11  Marzo                   1589462 non-null  object
 12  Abril                   1589462 non-null  object
 13  Mayo                    1589462 non-null  object
 14  Junio                   1589462 non-null  object
 15  Julio                   1589462 non-null  object
 16  Agosto                  1589462 non-null  object
 17  Septiembre              1589462 non-null  object
 18  Octubre                 1589462 non-null  object
 19  Noviembre               1589462 non-null  object
 20  Diciembre               1589462 non-null  object
dtypes: int64(3), object(18)
memory usage: 254.7+ MB

In [4]:
df['Entidad'] = df['Entidad'].astype("string")
df['Municipio'] = df['Municipio'].astype("string")
df['Bien_jurídico_afectado'] = df['Bien_jurídico_afectado'].astype("string")
df['Tipo_de_delito'] = df['Tipo_de_delito'].astype("string")
df['Subtipo_de_delito'] = df['Subtipo_de_delito'].astype("string")
df['Modalidad'] = df['Modalidad'].astype("string")
df['Enero'] = df['Enero'].astype("int64")
df['Febrero'] = df['Febrero'].astype("int64")
df['Marzo'] = df['Marzo'].astype("int64")
df['Abril'] = df['Abril'].astype("int64")
df['Mayo'] = df['Mayo'].astype("int64")
df['Junio'] = df['Junio'].astype("int64")
df['Julio'] = df['Julio'].astype("int64")
df['Agosto'] = df['Agosto'].astype("int64")
df['Septiembre'] = df['Septiembre'].astype("int64")
df['Octubre'] = df['Octubre'].astype("int64")
df['Noviembre'] = df['Noviembre'].astype("int64")
df['Diciembre'] = df['Diciembre'].astype("int64")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1589462 entries, 0 to 1589461
Data columns (total 21 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Año                     1589462 non-null  int64
 1   Clave_Ent               1589462 non-null  int64
 2   Entidad                 1589462 non-null  string
 3   Cve_Municipio           1589462 non-null  int64
 4   Municipio               1589462 non-null  string
 5   Bien_jurídico_afectado  1589462 non-null  string
 6   Tipo_de_delito          1589462 non-null  string
 7   Subtipo_de_delito       1589462 non-null  string
 8   Modalidad               1589462 non-null  string
 9   Enero                   1589462 non-null  int64
 10  Febrero                 1589462 non-null  int64
 11  Marzo                   1589462 non-null  int64
 12  Abril                   1589462 non-null  int64
 13  Mayo                    1589462 non-null  int64
 14  Junio                   1589462 non-null  int64
 15  Julio                   1589462 non-null  int64
 16  Agosto                  1589462 non-null  int64
 17  Septiembre              1589462 non-null  int64
 18  Octubre                 1589462 non-null  int64
 19  Noviembre               1589462 non-null  int64
 20  Diciembre               1589462 non-null  int64
dtypes: int64(15), string(6)
memory usage: 254.7 MB

In [5]:
df.nunique()

Año                          7
Clave_Ent                   32
Entidad                     32
Cve_Municipio             2478
Municipio                 2331
Bien_jurídico_afectado       7
Tipo_de_delito              40
Subtipo_de_delito           55
Modalidad                   59
Enero                      409
Febrero                    418
Marzo                      446
Abril                      437
Mayo                       458
Junio                      446
Julio                      446
Agosto                     456
Septiembre                 445
Octubre                    459
Noviembre                  432
Diciembre                  424
dtype: int64

In [22]:
# Número promedio de delitos agrupados por municipio y año-mes de ocurrencia de estos.


# Paso 1: Transformar los datos de columnas de meses a filas (de forma larga)
df_melted = df.melt(
    id_vars=['Año', 'Clave_Ent', 'Entidad', 'Cve_Municipio', 'Municipio', 'Tipo_de_delito', 'Subtipo_de_delito'], 
    value_vars=['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 
                'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    var_name='Mes', 
    value_name='Delitos'
)

# Paso 2: Mapear los meses a números
mes_a_num = {
    'Enero': 1, 'Febrero': 2, 'Marzo': 3, 'Abril': 4, 'Mayo': 5, 'Junio': 6, 
    'Julio': 7, 'Agosto': 8, 'Septiembre': 9, 'Octubre': 10, 'Noviembre': 11, 'Diciembre': 12
}
df_melted['Mes'] = df_melted['Mes'].map(mes_a_num)

# Paso 3: Crear una columna de "Año-Mes"
df_melted['Año_Mes'] = pd.to_datetime({
    'year': df_melted['Año'], 
    'month': df_melted['Mes'], 
    'day': 1
})

# Paso 4: Agrupar por Municipio y Año-Mes, y calcular el promedio de delitos
resultado = df_melted.groupby(['Municipio', 'Año_Mes'])['Delitos'].mean().reset_index()

# Paso 5: Renombrar las columnas para claridad
resultado.columns = ['Municipio', 'Año_Mes', 'Promedio_Delitos']

# Mostrar el resultado
resultado.sort_values(by='Promedio_Delitos', ascending=False).head(20)

                  Municipio    Año_Mes  Promedio_Delitos
49032           Guadalajara 2019-01-01         53.040816
49015           Guadalajara 2017-08-01         51.500000
49017           Guadalajara 2017-10-01         50.826531
49024           Guadalajara 2018-05-01         49.418367
49022           Guadalajara 2018-03-01         48.214286
157953              Tijuana 2015-10-01         47.704082
49016           Guadalajara 2017-09-01         47.693878
70267                  León 2021-08-01         47.663265
157952              Tijuana 2015-09-01         47.510204
42009   Ecatepec de Morelos 2017-10-01         47.316327
157949              Tijuana 2015-06-01         47.234694
157951              Tijuana 2015-08-01         47.051020
49018           Guadalajara 2017-11-01         46.846939
49039           Guadalajara 2019-08-01         46.663265
157975              Tijuana 2017-08-01         46.571429
49014           Guadalajara 2017-07-01         46.500000
158001              Tijuana 2019-10-01         46.489796
49026           Guadalajara 2018-07-01         46.438776
49013           Guadalajara 2017-06-01         46.204082
157950              Tijuana 2015-07-01         46.193878

In [7]:

# El delito más común por municipio

# Paso 1: Contar la frecuencia de cada tipo de delito por municipio
delito_frecuente = (
    df.groupby(['Municipio', 'Tipo_de_delito'])
    .size()  # Contar la frecuencia
    .reset_index(name='Frecuencia')  # Renombrar la columna del conteo
)

# Paso 2: Identificar el delito más común por municipio
delito_mas_comun = (
    delito_frecuente.loc[
        delito_frecuente.groupby('Municipio')['Frecuencia'].idxmax()
    ]
)

# Paso 3: Renombrar las columnas para claridad
delito_mas_comun.columns = ['Municipio', 'Tipo_de_delito', 'Frecuencia']

# Mostrar el resultado
delito_mas_comun.sort_values(by="Frecuencia", ascending=False).head(20)

                 Municipio Tipo_de_delito  Frecuencia
8112         Benito Juárez           Robo        1764
41712               Ocampo           Robo        1512
21552      Emiliano Zapata           Robo        1404
32072               Juárez           Robo        1260
40912      No Especificado           Robo        1260
39072              Morelos           Robo        1260
24992              Hidalgo           Robo        1260
87992        Villa Hidalgo           Robo        1188
72                 Abasolo           Robo        1008
23872            Guadalupe           Robo        1008
87432  Venustiano Carranza           Robo        1008
85752               Tuxpan           Robo        1008
30712              Jiménez           Robo        1008
92112             Zaragoza           Robo        1008
46912                Rayón           Robo        1008
18152           Cuauhtémoc           Robo        1008
36272            Matamoros           Robo         756
24512         Gómez Farías           Robo         756
42912     Otros Municipios           Robo         756
36992       Melchor Ocampo           Robo         756

In [8]:
df.sample(5)

,Año,Clave_Ent,Entidad,Cve_Municipio,Municipio,Bien_jurídico_afectado,Tipo_de_delito,Subtipo_de_delito,Modalidad,Enero,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
816299,2018,28,Tamaulipas,28012,González,El patrimonio,Robo,Robo en transporte público colectivo,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0
1281439,2020,22,Querétaro,22013,Peñamiller,Otros bienes jurídicos afectados (del fuero co...,Amenazas,Amenazas,Amenazas,0,...,2,3,0,5,0,2,1,0,0,3
727359,2016,15,México,15054,Metepec,El patrimonio,Robo,Robo de vehículo automotor,Robo de coche de 4 ruedas Con violencia,6,...,13,8,6,5,2,1,12,12,9,9
1543020,2021,28,Tamaulipas,28008,Casas,La vida y la Integridad corporal,Lesiones,Lesiones dolosas,Con arma blanca,0,...,0,0,0,0,0,0,0,0,0,0
919491,2019,14,Jalisco,14047,Jamay,El patrimonio,Robo,Robo en transporte público individual,Con violencia,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# Temporada con más crímenes en México

import pandas as pd


# Paso 1: Agrupar los datos por 'Año_Mes' y calcular el total de crímenes
temporada_crimenes = (
    df_melted.groupby('Año_Mes')['Delitos']
    .sum()
    .reset_index(name='Total_Delitos')
)

# Paso 2: Identificar la temporada con más crímenes
temporada_max = temporada_crimenes.loc[temporada_crimenes['Total_Delitos'].idxmax()]

# Mostrar la temporada con más crímenes
print("La temporada con más crímenes:")
print(temporada_max)

La temporada con más crímenes:
Año_Mes          2019-05-01 00:00:00
Total_Delitos                 185802
Name: 52, dtype: object

In [15]:
df_melted.sample(5)

,Año,Clave_Ent,Entidad,Cve_Municipio,Municipio,Tipo_de_delito,Mes,Delitos,Año_Mes
15126302,2018,29,Tlaxcala,29019,Tepetitla de Lardizábal,Homicidio,10,0,2018-10-01
9558848,2016,21,Puebla,21005,Acteopan,Robo,7,0,2016-07-01
13777112,2019,28,Tamaulipas,28042,Villagrán,Abuso de confianza,9,0,2019-09-01
5792044,2019,21,Puebla,21071,Huauchinango,Robo,4,1,2019-04-01
4828835,2016,26,Sonora,26999,Otros Municipios,Otros delitos que atentan contra la vida y la ...,4,0,2016-04-01

In [17]:
# El número promedio de delitos agrupados por tipo de delito y año y mes en la ciudad de México ordenados de mayor a menor


# Paso 1: Filtrar los datos para obtener solo los de Ciudad de México
df_cdmx = df_melted[df_melted['Entidad'] == 'Ciudad de México']

# Paso 2: Agrupar por 'Tipo_de_delito' y 'Año_Mes', y calcular el promedio de delitos
promedio_delitos = (
    df_cdmx.groupby(['Tipo_de_delito', 'Año_Mes'])['Delitos']
    .mean()  # Calcular el promedio
    .reset_index(name='Promedio_Delitos')  # Reiniciar el índice
)

# Paso 3: Ordenar de mayor a menor el promedio de delitos
promedio_delitos = promedio_delitos.sort_values(by='Promedio_Delitos', ascending=False)

# Mostrar los resultados
promedio_delitos

,Tipo_de_delito,Año_Mes,Promedio_Delitos
3350,Violencia familiar,2021-03-01,193.941176
3352,Violencia familiar,2021-05-01,189.000000
3351,Violencia familiar,2021-04-01,184.705882
3357,Violencia familiar,2021-10-01,181.117647
3353,Violencia familiar,2021-06-01,175.882353
...,...,...,...
2536,Otros delitos que atentan contra la vida y la ...,2016-05-01,0.000000
2537,Otros delitos que atentan contra la vida y la ...,2016-06-01,0.000000
2538,Otros delitos que atentan contra la vida y la ...,2016-07-01,0.000000
2539,Otros delitos que atentan contra la vida y la ...,2016-08-01,0.000000
1680,Incesto,2015-01-01,0.000000

In [18]:
df.describe()

,Año,Clave_Ent,Cve_Municipio,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
count,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06,1.589462e+06
mean,2.018168e+03,1.920310e+01,1.930313e+04,6.556042e-01,6.587028e-01,7.259349e-01,6.774670e-01,7.109362e-01,7.083139e-01,7.038740e-01,7.204394e-01,7.052405e-01,7.422801e-01,6.918391e-01,6.704621e-01
std,1.951503e+00,7.589146e+00,7.604944e+03,7.834945e+00,7.781036e+00,8.592510e+00,8.172660e+00,8.531118e+00,8.415789e+00,8.379056e+00,8.611315e+00,8.254567e+00,8.608259e+00,8.095261e+00,8.052826e+00
min,2.015000e+03,1.000000e+00,1.001000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.017000e+03,1.400000e+01,1.404400e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.018000e+03,2.000000e+01,2.021000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.020000e+03,2.500000e+01,2.501100e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2.021000e+03,3.200000e+01,3.205800e+04,1.341000e+03,1.353000e+03,1.712000e+03,1.791000e+03,1.727000e+03,1.897000e+03,1.219000e+03,2.143000e+03,2.076000e+03,1.452000e+03,1.915000e+03,1.909000e+03

In [19]:
# Tabla de los 5 delitos mas cometidos por año


# Paso 1: Agrupar los datos por 'Año' y 'Tipo_de_delito' y calcular el total de delitos
delitos_por_anio = (
    df_melted.groupby(['Año', 'Tipo_de_delito'])['Delitos']
    .sum()  # Calcular el total de delitos por año y tipo de delito
    .reset_index()  # Reiniciar el índice
)

# Paso 2: Ordenar los datos dentro de cada año por el total de delitos
delitos_por_anio = delitos_por_anio.sort_values(by=['Año', 'Delitos'], ascending=[True, False])

# Paso 3: Obtener los 5 delitos más cometidos por cada año
top_5_delitos = delitos_por_anio.groupby('Año').head(5)

# Mostrar los resultados
print(top_5_delitos)

      Año                 Tipo_de_delito  Delitos
32   2015                           Robo   652647
22   2015                       Lesiones   207116
27   2015  Otros delitos del Fuero Común   173845
39   2015             Violencia familiar   127424
8    2015            Daño a la propiedad   120246
72   2016                           Robo   689355
62   2016                       Lesiones   197305
67   2016  Otros delitos del Fuero Común   196885
79   2016             Violencia familiar   153893
48   2016            Daño a la propiedad   122785
112  2017                           Robo   801099
102  2017                       Lesiones   204882
107  2017  Otros delitos del Fuero Común   185754
119  2017             Violencia familiar   169579
88   2017            Daño a la propiedad   129390
152  2018                           Robo   810602
142  2018                       Lesiones   198537
159  2018             Violencia familiar   180187
147  2018  Otros delitos del Fuero Común   167213
128  2018            Daño a la propiedad   132692
192  2019                           Robo   766096
182  2019                       Lesiones   210546
199  2019             Violencia familiar   210188
187  2019  Otros delitos del Fuero Común   169321
168  2019            Daño a la propiedad   135779
232  2020                           Robo   604275
239  2020             Violencia familiar   220031
222  2020                       Lesiones   182000
227  2020  Otros delitos del Fuero Común   160118
208  2020            Daño a la propiedad   116479
272  2021                           Robo   609237
279  2021             Violencia familiar   253739
262  2021                       Lesiones   200958
267  2021  Otros delitos del Fuero Común   195984
248  2021            Daño a la propiedad   137974

In [ ]:
#  Delitos totales en orden de frecuencia y porcentaje frente al total

import pandas as pd

# Paso 1: Agrupar los datos por 'Tipo_de_delito' y calcular el total de delitos
delitos_totales = (
    df_melted.groupby('Tipo_de_delito')['Delitos']
    .sum()  # Calcular el total de delitos por tipo de delito
    .reset_index()  # Reiniciar el índice
)

# Paso 2: Ordenar los resultados de mayor a menor
delitos_totales = delitos_totales.sort_values(by='Delitos', ascending=False)

# Paso 1: Calcular el total global de delitos
total_delitos = delitos_totales['Delitos'].sum()

# Paso 2: Agregar una columna de porcentaje
delitos_totales['Porcentaje'] = (delitos_totales['Delitos'] / total_delitos) * 100


# Mostrar los resultados
delitos_totales

                                       Tipo_de_delito  Delitos  Porcentaje
32                                               Robo  4933311   37.077131
22                                           Lesiones  1401344   10.532037
39                                 Violencia familiar  1315041    9.883412
27                      Otros delitos del Fuero Común  1249120    9.387972
8                                 Daño a la propiedad   895345    6.729116
5                                            Amenazas   650832    4.891438
17                                             Fraude   493028    3.705435
23                                       Narcomenudeo   395477    2.972274
18                                          Homicidio   284638    2.139245
10                                            Despojo   183328    1.377833
1                                  Abuso de confianza   172582    1.297069
21  Incumplimiento de obligaciones de asistencia f...   163909    1.231886
2                                        Abuso sexual   135592    1.019065
9           Delitos cometidos por servidores públicos   123704    0.929718
28  Otros delitos que atentan contra la libertad p...   119392    0.897311
15                                      Falsificación   117240    0.881137
4                              Allanamiento de morada    92230    0.693170
37                                   Violación simple    85874    0.645401
25                    Otros delitos contra la familia    80021    0.601411
24                 Otros delitos contra el patrimonio    69810    0.524669
30  Otros delitos que atentan contra la vida y la ...    51052    0.383690
13                                          Extorsión    50125    0.376723
29  Otros delitos que atentan contra la libertad y...    44663    0.335672
26                   Otros delitos contra la sociedad    39070    0.293637
36                               Violación equiparada    24201    0.181887
3                                        Acoso sexual    23721    0.178279
14                                           Falsedad    21399    0.160828
38  Violencia de género en todas sus modalidades d...    19351    0.145436
7                               Corrupción de menores    14738    0.110766
6                            Contra el medio ambiente    12828    0.096411
19                               Hostigamiento sexual     9732    0.073142
11                                        Electorales     9525    0.071587
33                                          Secuestro     7457    0.056044
16                                        Feminicidio     5519    0.041479
0                                              Aborto     4311    0.032400
34                                  Trata de personas     3208    0.024110
31                                              Rapto     1218    0.009154
12                                  Evasión de presos      843    0.006336
35                                 Tráfico de menores      593    0.004457
20                                            Incesto      164    0.001233

In [23]:
#  Tabla de frecuencia y % de ocurrencia para los tipos de robos

# Paso 1: Filtrar los datos por Tipo_de_delito = "Robo"
df_robo = df_melted[df_melted['Tipo_de_delito'] == 'Robo']

# Paso 2: Agrupar por Subtipo_de_delito y calcular la frecuencia
frecuencia_robos = (
    df_robo.groupby('Subtipo_de_delito')['Delitos']
    .sum()  # Sumar el número total de delitos por subtipo
    .reset_index()  # Reiniciar el índice
)

# Paso 3: Calcular el total global de robos
total_robos = frecuencia_robos['Delitos'].sum()

# Paso 4: Agregar la columna de porcentaje
frecuencia_robos['Porcentaje'] = (frecuencia_robos['Delitos'] / total_robos) * 100

# Paso 5: Ordenar los resultados de mayor a menor
frecuencia_robos = frecuencia_robos.sort_values(by='Delitos', ascending=False)

# Mostrar los resultados
frecuencia_robos

                                  Subtipo_de_delito  Delitos  Porcentaje
0                                       Otros robos  1422907   28.842840
10                       Robo de vehículo automotor  1234481   25.023377
3                                    Robo a negocio   684093   13.866813
1                            Robo a casa habitación   562433   11.400721
5                  Robo a transeúnte en vía pública   545073   11.048827
7                                Robo de autopartes   111417    2.258463
12             Robo en transporte público colectivo   107575    2.180584
11                    Robo en transporte individual    95505    1.935921
6                              Robo a transportista    71077    1.440757
8                                    Robo de ganado    40539    0.821740
4   Robo a transeúnte en espacio abierto al público    27243    0.552225
13            Robo en transporte público individual    16944    0.343461
9                                Robo de maquinaria    10937    0.221697
2                       Robo a institución bancaria     3087    0.062575

In [24]:
#  Tabla de frecuencia y % de ocurrencia para los tipos de lesiones

# Paso 1: Filtrar los datos por Tipo_de_delito = "Robo"
df_robo = df_melted[df_melted['Tipo_de_delito'] == 'Lesiones']

# Paso 2: Agrupar por Subtipo_de_delito y calcular la frecuencia
frecuencia_robos = (
    df_robo.groupby('Subtipo_de_delito')['Delitos']
    .sum()  # Sumar el número total de delitos por subtipo
    .reset_index()  # Reiniciar el índice
)

# Paso 3: Calcular el total global de robos
total_robos = frecuencia_robos['Delitos'].sum()

# Paso 4: Agregar la columna de porcentaje
frecuencia_robos['Porcentaje'] = (frecuencia_robos['Delitos'] / total_robos) * 100

# Paso 5: Ordenar los resultados de mayor a menor
frecuencia_robos = frecuencia_robos.sort_values(by='Delitos', ascending=False)

# Mostrar los resultados
frecuencia_robos

   Subtipo_de_delito  Delitos  Porcentaje
1   Lesiones dolosas  1059632   75.615409
0  Lesiones culposas   341712   24.384591

In [25]:
#  Tabla de frecuencia y % de ocurrencia para los tipos de Violencia familiar

# Paso 1: Filtrar los datos por Tipo_de_delito = "Robo"
df_robo = df_melted[df_melted['Tipo_de_delito'] == 'Violencia Familiar']

# Paso 2: Agrupar por Subtipo_de_delito y calcular la frecuencia
frecuencia_robos = (
    df_robo.groupby('Subtipo_de_delito')['Delitos']
    .sum()  # Sumar el número total de delitos por subtipo
    .reset_index()  # Reiniciar el índice
)

# Paso 3: Calcular el total global de robos
total_robos = frecuencia_robos['Delitos'].sum()

# Paso 4: Agregar la columna de porcentaje
frecuencia_robos['Porcentaje'] = (frecuencia_robos['Delitos'] / total_robos) * 100

# Paso 5: Ordenar los resultados de mayor a menor
frecuencia_robos = frecuencia_robos.sort_values(by='Delitos', ascending=False)

# Mostrar los resultados
frecuencia_robos

Empty DataFrame
Columns: [Subtipo_de_delito, Delitos, Porcentaje]
Index: []

In [26]:
#  Tabla de frecuencia y % de ocurrencia para los tipos de Daño a la propiedad

# Paso 1: Filtrar los datos por Tipo_de_delito = "Robo"
df_robo = df_melted[df_melted['Tipo_de_delito'] == 'Daño a la propiedad']

# Paso 2: Agrupar por Subtipo_de_delito y calcular la frecuencia
frecuencia_robos = (
    df_robo.groupby('Subtipo_de_delito')['Delitos']
    .sum()  # Sumar el número total de delitos por subtipo
    .reset_index()  # Reiniciar el índice
)

# Paso 3: Calcular el total global de robos
total_robos = frecuencia_robos['Delitos'].sum()

# Paso 4: Agregar la columna de porcentaje
frecuencia_robos['Porcentaje'] = (frecuencia_robos['Delitos'] / total_robos) * 100

# Paso 5: Ordenar los resultados de mayor a menor
frecuencia_robos = frecuencia_robos.sort_values(by='Delitos', ascending=False)

# Mostrar los resultados
frecuencia_robos

     Subtipo_de_delito  Delitos  Porcentaje
0  Daño a la propiedad   895345       100.0

In [30]:
#Exporto de la BD solo lo que se necesita para el informe con delitos relacionados con vehiculos

# Configuración de la conexión
server = 'localhost'  # Nombre o dirección del servidor SQL Server
database = 'Delitos'  # Nombre de tu base de datos
username = 'paob2'  # Usuario de SQL Server
password = 'Paulo2024$'  # Contraseña del usuario
driver = '{ODBC Driver 17 for SQL Server}'  # Asegúrate de tener el driver adecuado instalado

# Conexión a la base de datos
try:
    
    ##connection = pyodbc.connect(
    ##    f'DRIVER={driver};SERVER={server};DATABASE={database};UID={username};PWD={password}'
    ##)

    connection = pyodbc.connect(
    f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes'
)
    print("Conexión exitosa a la base de datos.")

    # Creación de un cursor
    cursor = connection.cursor()

    # Ejecución de una consulta
    query = "SELECT *, CAST(Enero AS INT) + CAST(Febrero AS INT) + CAST(Marzo AS INT) + CAST(Abril AS INT) + CAST(Mayo AS INT) + CAST(Junio AS INT) + CAST(Julio AS INT) + CAST(Agosto AS INT) + CAST(Septiembre AS INT) + CAST(Octubre AS INT) + CAST(Noviembre AS INT) + CAST(Diciembre AS INT) AS Total_year FROM Delitos.dbo.delitos WHERE (Subtipo_de_delito LIKE 'Robo de autopartes' OR Subtipo_de_delito LIKE 'Robo de vehículo automotor') AND (Modalidad LIKE 'Con violencia' OR Modalidad LIKE 'Sin violencia' OR Modalidad LIKE 'Robo de coche de 4 ruedas%');"  


        # Leer los datos en un DataFrame de Pandas
    df = pd.read_sql_query(query, connection)


except pyodbc.Error as e:
    print("Error al conectar a la base de datos:", e)

finally:
    # Cerrar la conexión
    if 'connection' in locals() and connection:
        connection.close()
        print("Conexión cerrada.")


df.to_csv("Delitos_sorted.csv", index=False)

Conexión exitosa a la base de datos.

C:\Users\paob2\AppData\Local\Temp\ipykernel_11292\3801578857.py:30: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)

Conexión cerrada.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64876 entries, 0 to 64875
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     64876 non-null  int64
 1   Clave_Ent               64876 non-null  int64
 2   Entidad                 64876 non-null  object
 3   Cve_Municipio           64876 non-null  int64
 4   Municipio               64876 non-null  object
 5   Bien_jurídico_afectado  64876 non-null  object
 6   Tipo_de_delito          64876 non-null  object
 7   Subtipo_de_delito       64876 non-null  object
 8   Modalidad               64876 non-null  object
 9   Enero                   64876 non-null  object
 10  Febrero                 64876 non-null  object
 11  Marzo                   64876 non-null  object
 12  Abril                   64876 non-null  object
 13  Mayo                    64876 non-null  object
 14  Junio                   64876 non-null  object
 15  Julio                   64876 non-null  object
 16  Agosto                  64876 non-null  object
 17  Septiembre              64876 non-null  object
 18  Octubre                 64876 non-null  object
 19  Noviembre               64876 non-null  object
 20  Diciembre               64876 non-null  object
 21  Total_year              64876 non-null  int64
dtypes: int64(4), object(18)
memory usage: 10.9+ MB